service:
  name: test-helper-default

plugins:
  - serverless-webpack
  - serverless-plugin-test-helper

provider:
  name: aws
  stage: example
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
